

#===================================================================
#  pptv.offshore
#===================================================================
#' Return table of values as would be seen in Offshore's PPTV report.
#' 
#' Bla, bla
#' 
#' @param pptv_data
#' 
#' @export
#$
pptv.offshore = function(
    pptv_data
) {
    print("Creating LIVE table...")
    live            = pptv.offshore.live(pptv_data)
    print("Creating LIVE+7 table...")
    lp7             = pptv.offshore.lp7(pptv_data)
    print("Creating  SHORTFORM table...")
    shortform       = pptv.offshore.shortform(pptv_data)
    print("Creating TOP20 table...")
    top20           = pptv.offshore.topmatches(pptv_data)
    print("Creating TOTALS OVERVIEW table...")
    total_overview  = pptv.offshore.overview(pptv_data)
    print("Creating LIVE OVERVIEW table...")
    live_overview   = pptv.offshore.overview(pptv_data, type="live")
    print("Creating WEB table...")
    web             = pptv.offshore.web()
    
    list(live=live, lp7=lp7, shortform=shortform, 
         top20=top20, total_overview=total_overview, 
         live_overview=live_overview, web=web)
    
}




#===================================================================
#  pptv.offshore.live
#===================================================================
#   2017-02-06, Kevin Urban (created)
#===================================================================
#' Generate numbers given in the report for Live, Full Episode 
#' 
#' This function returns the Live unique viewer and minute counts which correspond
#' to the most recently aired Raw and Smackdown full-length episodes 
#' relative to the provided as_on_dt. Additionally, it returns the
#' "Vs 4-Week Avg" KPIs found in report generated by the offshore
#' EXL team:
#' 
#' COMPUTE TRAILING 4-WEEK AVERAGE
#' trlAvg = avg(cnt_1wkAgo, cnt_2wksAgo, cnt_3wksAgo, cnt_4wksAgo)
#'   
#' COMPUTE THE DELTA (PERCENT DIFF BETWEEN THIS WEEK AND TRLNG AVG )
#' thisWksCnt - trlAvg            
#' --------------------- * 100\%   
#' trlAvg                   
#'
#' The script was designed (in conjunction with most of the pptvR package)
#' to reverse engineer the numbers given in the PPTV report generated by the 
#' offshore EXL team.  For as long as the offshore EXL team is in charge
#' of generating the report, this script serves as a double
#' check to ensure no copy-and-paste errors have made their 
#' way into the report, which has happened from time to time.
#' 
#' @param pptv_data
#' PPTV data set
#' 
#' @param View (optional; {TRUE|FALSE} or {0|1})
#' By default (FALSE) data is returned to parent environment
#' (whether that is to a variable or to screen). By
#' flagging View (TRUE), the data is instead routed to 
#' View()
#' 
#' @return Live, Full Episode metrics and KPIs for
#' the Raw and Smackdown episodes aired most recently
#' relative to the user-provided as_on_dt.         
#' 
#' @examples 
#' data = pptv.report.live("2017-03-09")
#'          
#' @export        
pptv.offshore.live = function(
    pptv_data, 
    View=FALSE
) {
  
  #-------------------------------------------
  #--------        Get Data       ------------
  #-------------------------------------------
  as_on_dt = as.Date(max(pptv_data$dataDate)) + lubridate::days(1)
  
  # [1] LIVE DATA IN MOST RECENT 5-WK WINDOW
  trlng = as.data.frame(pptv.live(pptv_data,trail=5))
  
  # [2] Include Totals in Data Set
  tot = trlng %>% 
      dplyr::group_by(
          usAirDate, chinaAirDate, show#, payment
      ) %>%
      dplyr::summarize(
          audio    ='All', 
          subtitle ='All',
          totUniq  = sum(totUniq), 
          totView  = sum(totView),
          totMin   = sum(totMin)
      ) %>%
      as.data.frame()
  
  trlng=rbind(trlng, tot)
  
  # [3] MOST RECENT LIVE DATA
  LIVE = trlng %>%
    dplyr::filter(chinaAirDate >= as_on_dt - lubridate::days(7))
  
  # [4] TRAILING 4-Wk AVERAGE (Non-Inclusive)
  trlngAvg = trlng %>%
    dplyr::filter(
        chinaAirDate<=as_on_dt - lubridate::days(7)
        ) %>%
    dplyr::group_by(
        show, audio
        ) %>%
    dplyr::summarize(
        usAirDate     = max(usAirDate) + lubridate::days(7),
        trlAvgTotUniq = mean(totUniq),
        trlAvgTotView = mean(totView),
        trlAvgTotMin  = mean(totMin))
  
  # [4] JOIN LIVE w/ Trailing Avgs
  #  -- Offshore team reports to nearest integer
  output = dplyr::inner_join(
        LIVE, trlngAvg,
        by=c("usAirDate","show","audio")
        ) %>%
    dplyr::transmute(
        usAirDate, show, audio, subtitle, totUniq, totView, totMin, 
        totUniqVs4WkAvg = round(100*(totUniq-trlAvgTotUniq)/trlAvgTotUniq),
        totViewVs4WkAvg = round(100*(totView-trlAvgTotView)/trlAvgTotView),
        totMinVs4WkAvg = round(100*(totMin-trlAvgTotMin)/trlAvgTotMin)
    ) %>%
    dplyr::arrange(
        usAirDate, 
        show, 
        dplyr::desc(audio))
  
  if(View==FALSE) { return(as.data.frame(output)) } else { View(output) }
}  




#===================================================================
#  pptv.offshore.lp7
#===================================================================
#   2017-02-09, Kevin Urban (created)
#===================================================================
#' Generate numbers given in the report for Live+7, Full Episode 
#' 
#' This function returns the Live+7 unique viewer and minute counts which correspond
#' to the most recently aired Raw and Smackdown full-length episodes 
#' relative to the provided as_on_dt. Additionally, it returns the
#' "Vs 4-Week Avg" KPIs found in report generated by the offshore
#' EXL team:
#' 
#' COMPUTE TRAILING 4-WEEK AVERAGE
#' trlAvg = avg(cnt_1wkAgo, cnt_2wksAgo, cnt_3wksAgo, cnt_4wksAgo)
#' 
#' COMPUTE THE DELTA (PERCENT DIFF BETWEEN THIS WEEK AND TRLNG AVG )
#' thisWksCnt - trlAvg            
#' --------------------- * 100\%   
#' trlAvg                   
#' 
#' The script was designed (in conjunction with most of the pptvR package)
#' to reverse engineer the numbers given in the PPTV report generated by the 
#' offshore EXL team.  For as long as the offshore EXL team is in charge
#' of generating the report, this script serves as a double
#' check to ensure no copy-and-paste errors have made their 
#' way into the report, which has happened from time to time.
#' 
#' @param as_on_dt (character or Date)
#' User may provide any date in the form YYYY-MM-DD, 
#' however it will be converted to the nearest, 
#' previous as_on_dt for which PPTV provided a data 
#' set.
#'          
#' @param View (optional; {TRUE|FALSE} or {0|1})
#' By default (FALSE) data is returned to parent environment
#' (whether that is to a variable or to screen). By
#' flagging View (TRUE), the data is instead routed to 
#' View()
#' 
#' @return Live+7, Full Episode metrics and KPIs for
#' the Raw and Smackdown episodes aired most recently
#' relative to the user-provided as_on_dt.         
#' 
#' @examples 
#' data = pptv.offshore.lp7("2017-03-09")
#'          
#' @export        
pptv.offshore.lp7 = function(
    pptv_data, 
    View=FALSE, 
    uniques=FALSE
) {
  
  #-------------------------------------------
  #--------        Get Data       ------------
  #-------------------------------------------
  as_on_dt = as.Date(max(pptv_data$dataDate)) + lubridate::days(1)
  
  # [1] LIVE DATA IN MOST RECENT 5-WK WINDOW
  trlng = as.data.frame(pptv.lp7(pptv_data, trail=5, agg=1))
  
  # [2a] Include Totals in Data Set
  totals = trlng %>% 
      dplyr::group_by(
          usAirDate, chinaAirDate, show
          ) %>%
      dplyr::summarize(
          audio    ='All', 
          subtitle ='All',
          totUniq  = sum(totUniq), 
          totView  = sum(totView),
          totMin   = sum(totMin)
          ) %>%
      as.data.frame()
  # NOTE: converted to data.frame b/c rbind is weird
  #   w/ tibbles.  Might be something better than rbind.
  
  # [2a] Include English Totals in Data Set
  trlng = rbind(trlng, totals)
  eng   = trlng %>% 
      dplyr::filter(
          audio=='English'
          ) %>%
      dplyr::group_by(
          usAirDate, chinaAirDate, show
          ) %>%
      dplyr::summarize(
          audio    = 'English', 
          subtitle = 'All',
          totUniq  = sum(totUniq), 
          totView  = sum(totView),
          totMin   = sum(totMin)
      ) %>%
      as.data.frame()   # rbind is weird w/ tibbles
  
  
  # [3] MOST RECENT L+7 DATA
  trlng = rbind(trlng, eng)
  LP7  = trlng %>%
      dplyr::filter(
          chinaAirDate >= as_on_dt - lubridate::weeks(2),
          chinaAirDate < as_on_dt - lubridate::weeks(1))
  
  # [4] TRAILING 4-Wk AVERAGE (Non-Inclusive)
  trlngAvg = trlng %>%
      dplyr::filter(
          chinaAirDate <= as_on_dt - lubridate::weeks(2)
      ) %>% 
      dplyr::group_by(
          show, audio, subtitle
      ) %>%
      dplyr::summarize(
          usAirDate     = max(usAirDate) + lubridate::days(7),
          trlAvgTotUniq = mean(totUniq),
          trlAvgTotView = mean(totView),
          trlAvgTotMin  = mean(totMin))
  
  # [4] JOIN LP7 w/ Trailing Avgs
  #  -- Offshore team reports to nearest integer
  output = LP7 %>%
      dplyr::inner_join(
          trlngAvg,
          by=c("usAirDate","show","audio","subtitle")
          ) 
  
  if (uniques==FALSE) {
      output = output %>% dplyr::transmute(
          usAirDate, show, audio, subtitle, totView, totMin,
          totViewVs4WkAvg = round(100*(totView-trlAvgTotView)/trlAvgTotView),
          totMinVs4WkAvg  = round(100*(totMin-trlAvgTotMin)/trlAvgTotMin)) 
  } else {
      output = output %>% dplyr::transmute(
          usAirDate, show, audio, subtitle, totUniq, totView, totMin,
          totUniqVs4WkAvg = round(100*(totUniq-trlAvgTotUniq)/trlAvgTotUniq),
          totViewVs4WkAvg = round(100*(totView-trlAvgTotView)/trlAvgTotView),
          totMinVs4WkAvg  = round(100*(totMin-trlAvgTotMin)/trlAvgTotMin))
  }
  
  output = output %>%  dplyr::arrange(usAirDate, show, dplyr::desc(audio))
  
  # DONE
  if(View==FALSE) { return(output) } else { View(output) }
}  




#===================================================================
#  pptv.offshore.overview
#===================================================================
#  Created 2017-04-21 (Kevin Urban)
#===================================================================
#' Compute numbers for "Total Viewership" and "Live Viewership" presented
#' on last page of Offshore Report.
#' 
#' This function will give you the numbers for Raw, Smackdown, Other,
#' and Total.  
#' 
#' @param pptv_data
#' Must input a PPTV data set, e.g., pptv_data = pptv.excel(as_on_dt).
#' 
#' @param type (default: "Total")
#' Specify either "Total Viewership" or "Live Viewership".  Note that
#' this parameter is not case sensitive and only depends on the first
#' letter (e.g., "LIVE" and "l" will both yield numbers for "Live 
#' Viewership").
#' 
#' @param all_vars
#' Default=FALSE. If TRUE, returns uniques too.
#' 
#' @export
pptv.offshore.overview = function(
    pptv_data, 
    type="Total",
    all_vars=FALSE
) {
    
    as_on_dt = as.Date(max(pptv_data$dataDate)) + lubridate::days(1)
    type = substring(tolower(type), 1, 1) # "t" or "l"
    
    thisYear           = lubridate::year(as_on_dt)
    thisMonth          = lubridate::month(as_on_dt)
    oneMonthBack       = lubridate::month(as_on_dt - months(1))
    twoMonthsBack      = lubridate::month(as_on_dt - months(2))
    threeMonthsBack    = lubridate::month(as_on_dt - months(3))
    thisMonthDay1      = as.Date(paste(thisYear,thisMonth,1),      format="%Y %m %d")
    lastMonthDay1      = as.Date(paste(thisYear,oneMonthBack,1),   format="%Y %m %d")
    twoMonthsAgoDay1   = as.Date(paste(thisYear,twoMonthsBack,1),  format="%Y %m %d")
    threeMonthsAgoDay1 = as.Date(paste(thisYear,threeMonthsBack,1),format="%Y %m %d")
    
    if (type=="l") {
        pptv_data = pptv_data %>% dplyr::filter(type=="LIVE")
    }
    
    output = pptv_data %>% 
        dplyr::mutate(
            show = ifelse(show=='Smackdown*','Smackdown',show),
            show = ifelse(show!='Smackdown', ifelse(show!='Mon Night Raw','Other',show), show),
            show_order = ifelse(show=="Mon Night Raw", 0, 
                                ifelse(show=="Smackdown", 1, 2)),
            hours_MTD = ifelse(dataDate >= thisMonthDay1, totMin/60., 0),
            hours_lastMonth     = ifelse(dataDate >= lastMonthDay1 & dataDate < thisMonthDay1, totMin/60., 0),
            hours_twoMonthsAgo   = ifelse(dataDate >= twoMonthsAgoDay1 & dataDate < lastMonthDay1, totMin/60., 0),
            hours_threeMonthsAgo = ifelse(dataDate >= threeMonthsAgoDay1 & dataDate < twoMonthsAgoDay1, totMin/60., 0),
            uniqs_MTD = ifelse(dataDate >= thisMonthDay1, totUniq, 0),
            uniqs_lastMonth     = ifelse(dataDate >= lastMonthDay1 & dataDate < thisMonthDay1, totUniq, 0),
            uniqs_twoMonthsAgo   = ifelse(dataDate >= twoMonthsAgoDay1 & dataDate < lastMonthDay1, totUniq, 0),
            uniqs_threeMonthsAgo = ifelse(dataDate >= threeMonthsAgoDay1 & dataDate < twoMonthsAgoDay1, totUniq, 0),
            views_MTD = ifelse(dataDate >= thisMonthDay1, totView, 0),
            views_lastMonth     = ifelse(dataDate >= lastMonthDay1 & dataDate < thisMonthDay1, totView, 0),
            views_twoMonthsAgo   = ifelse(dataDate >= twoMonthsAgoDay1 & dataDate < lastMonthDay1, totView, 0),
            views_threeMonthsAgo = ifelse(dataDate >= threeMonthsAgoDay1 & dataDate < twoMonthsAgoDay1, totView, 0)
        ) %>%
        dplyr::group_by(show) %>% #, show_order) %>% 
        dplyr::summarize(
            show_order           = max(show_order),
            hours_MTD              = round(sum(hours_MTD)/1000),
            hours_lastMonth      = round(sum(hours_lastMonth)/1000),
            hours_twoMonthsAgo   = round(sum(hours_twoMonthsAgo)/1000),
            hours_threeMonthsAgo = round(sum(hours_threeMonthsAgo)/1000),
            hours_SinceLaunch    = round(sum(totMin/60.)/1000),
            uniqs_MTD            = round(sum(uniqs_MTD)/1000),
            uniqs_lastMonth      = round(sum(uniqs_lastMonth)/1000),
            uniqs_twoMonthsAgo   = round(sum(uniqs_twoMonthsAgo)/1000),
            uniqs_threeMonthsAgo = round(sum(uniqs_threeMonthsAgo)/1000),
            uniqs_SinceLaunch    = round(sum(totUniq)/1000),
            views_MTD            = round(sum(views_MTD)/1000),
            views_lastMonth      = round(sum(views_lastMonth)/1000),
            views_twoMonthsAgo   = round(sum(views_twoMonthsAgo)/1000),
            views_threeMonthsAgo = round(sum(views_threeMonthsAgo)/1000),
            views_SinceLaunch    = round(sum(totView)/1000)
        )  
    
    output = output %>% 
        dplyr::summarize(
            show="Total", 
            show_order=3,
            hours_MTD             = sum(hours_MTD), 
            hours_SinceLaunch     = sum(hours_SinceLaunch),
            hours_lastMonth       = sum(hours_lastMonth),
            hours_twoMonthsAgo    = sum(hours_twoMonthsAgo),
            hours_threeMonthsAgo  = sum(hours_threeMonthsAgo),
            uniqs_MTD             = sum(uniqs_MTD), 
            uniqs_SinceLaunch     = sum(uniqs_SinceLaunch),
            uniqs_lastMonth       = sum(uniqs_lastMonth),
            uniqs_twoMonthsAgo    = sum(uniqs_twoMonthsAgo),
            uniqs_threeMonthsAgo  = sum(uniqs_threeMonthsAgo),
            views_MTD             = sum(views_MTD), 
            views_SinceLaunch     = sum(views_SinceLaunch),
            views_lastMonth       = sum(views_lastMonth),
            views_twoMonthsAgo    = sum(views_twoMonthsAgo),
            views_threeMonthsAgo  = sum(views_threeMonthsAgo)
        ) %>%
        rbind(output) %>%
        dplyr::arrange(show_order)
    
    output = output %>% 
        tidyr::gather(Metric, Value, -show, -show_order) %>% 
        tidyr::separate(Metric,into=c("Metric", "Interval")) %>% 
        tidyr::spread(Interval, Value) %>% 
        dplyr::arrange(desc(Metric),show_order) %>% 
        dplyr::mutate(Vwrshp="Total") %>%
        dplyr::select(Vwrshp, show, Metric, MTD, lastMonth, twoMonthsAgo, threeMonthsAgo, SinceLaunch)
    # WTF did I intend w/ the Vwrship column?!?!
    
    colnames(output) = c("Viewership", "Show", "Metric", "MTD",
                       as.character(lubridate::month(oneMonthBack,lab=1)), 
                       as.character(lubridate::month(twoMonthsBack,lab=1)),
                       as.character(lubridate::month(threeMonthsBack,lab=1)),
                       "SinceLaunch")
    
    # OUTPUT
    if (all_vars==TRUE) {
        output
    } else {
        output %>% dplyr::slice(c(1:4,9:12))
    }
    
}




#===================================================================
#  pptv.offshore.shortform
#===================================================================
#' Return table of values as would be seen on Short Form page of
#' Offshore's PPTV report.
#' 
#' Bla, bla
#' 
#' @param pptv_data
#' 
#' @param N
#' 
#' @param v2
#' In mid-May 2017, we changed the format of this page quite a bit.
#' Set to FALSE to view old way of doing it.
#' 
#' @param all_vars
#' 
#' @export
pptv.offshore.shortform = function(
    pptv_data,
    N=3,
    v2=TRUE,
    all_vars=FALSE
) {
    if (v2==TRUE) {
        pptv.offshore.shortform.v2(pptv_data, N=N, all_vars=all_vars)
    } else {
        pptv.offshore.shortform.v1(pptv_data, N=N, all_vars=all_vars)
    }
}
pptv.offshore.shortform.v1 = function(
    pptv_data,
    N=3,
    all_vars=FALSE
) {
    #========================================================
    # Raw
    #========================================================
    output = pptv_data %>% 
        dplyr::filter(
            version=='Other', #chinaAirDate>'2017-01-20', 
            show == 'Mon Night Raw') %>% 
        dplyr::mutate(
            year = lubridate::year(chinaAirDate),
            week = lubridate::week(chinaAirDate),
            wday = ifelse(show=='Mon Night Raw',  'Monday', 'Tuesday'),
            usAirDate = as.Date(paste(year,week,wday), format="%Y %U %A"),
            chinaAirDate = usAirDate + lubridate::days(1))  %>%
        dplyr::group_by(
            #usAirDate, chinaAirDate, show, showTitle)       %>% 
            showTitle)       %>% 
        dplyr::summarize(
            totView = sum(totView),
            totMin  = round(sum(totMin)),
            totUniq = sum(totUniq),
            minsPerUniq = round(totMin/totUniq,1),
            minsPerView = round(totMin/totView,1)
            ) %>% 
        dplyr::arrange(dplyr::desc(showTitle)) %>% 
        dplyr::ungroup() %>%
        dplyr::mutate(
            orderNum=1,
            v1 = dplyr::lead(totView, 1, order_by=dplyr::desc(showTitle)),
            v2 = dplyr::lead(totView, 2, order_by=dplyr::desc(showTitle)),
            v3 = dplyr::lead(totView, 3, order_by=dplyr::desc(showTitle)),
            v4 = dplyr::lead(totView, 4, order_by=dplyr::desc(showTitle)),
            vLast4Avg = (v1+v2+v3+v4)/4.0,
            vVsLast4  = round(100 * (totView - vLast4Avg) / vLast4Avg),
            m1 = dplyr::lead(totMin, 1, order_by=dplyr::desc(showTitle)),
            m2 = dplyr::lead(totMin, 2, order_by=dplyr::desc(showTitle)),
            m3 = dplyr::lead(totMin, 3, order_by=dplyr::desc(showTitle)),
            m4 = dplyr::lead(totMin, 4, order_by=dplyr::desc(showTitle)),
            mLast4Avg = (m1+m2+m3+m4)/4.0,
            mVsLast4  = round(100 * (totMin - mLast4Avg) / mLast4Avg),
            u1 = dplyr::lead(totUniq, 1, order_by=dplyr::desc(showTitle)),
            u2 = dplyr::lead(totUniq, 2, order_by=dplyr::desc(showTitle)),
            u3 = dplyr::lead(totUniq, 3, order_by=dplyr::desc(showTitle)),
            u4 = dplyr::lead(totUniq, 4, order_by=dplyr::desc(showTitle)),
            uLast4Avg = (u1+u2+u3+u4)/4.0,
            uVsLast4  = round(100 * (totUniq - uLast4Avg) / uLast4Avg),
            mpu1 = dplyr::lead(minsPerUniq, 1, order_by=dplyr::desc(showTitle)),
            mpu2 = dplyr::lead(minsPerUniq, 2, order_by=dplyr::desc(showTitle)),
            mpu3 = dplyr::lead(minsPerUniq, 3, order_by=dplyr::desc(showTitle)),
            mpu4 = dplyr::lead(minsPerUniq, 4, order_by=dplyr::desc(showTitle)),
            mpuLast4Avg = (mpu1 + mpu2 + mpu3 + mpu4)/4.0,
            mpuVsLast4  = round(100 * (minsPerUniq - mpuLast4Avg) / mpuLast4Avg),
            mpv1 = dplyr::lead(minsPerView, 1, order_by=dplyr::desc(showTitle)),
            mpv2 = dplyr::lead(minsPerView, 2, order_by=dplyr::desc(showTitle)),
            mpv3 = dplyr::lead(minsPerView, 3, order_by=dplyr::desc(showTitle)),
            mpv4 = dplyr::lead(minsPerView, 4, order_by=dplyr::desc(showTitle)),
            mpvLast4Avg = (mpv1+mpv2+mpv3+mpv4)/4.0,
            mpvVsLast4  = round(100 * (minsPerView - mpvLast4Avg) / mpvLast4Avg)
        ) %>%
        dplyr::select(-c(
            v1,v2,v3,v4,vLast4Avg,
            m1,m2,m3,m4, mLast4Avg,
            u1,u2,u3,u4,uLast4Avg,
            mpu1,mpu2,mpu3,mpu4,mpuLast4Avg,
            mpv1,mpv2,mpv3,mpv4,mpvLast4Avg
            )) %>%
        dplyr::slice(1:N) 
    
    #========================================================
    # Smackdown
    #========================================================
    output = pptv_data %>% 
        dplyr::filter(
            version=='Other', #chinaAirDate>'2017-01-20', 
            show == 'Smackdown') %>% 
        dplyr::mutate(
            year = lubridate::year(chinaAirDate),
            week = lubridate::week(chinaAirDate),
            wday = ifelse(show=='Mon Night Raw',  'Monday', 'Tuesday'),
            usAirDate = as.Date(paste(year,week,wday), format="%Y %U %A"),
            chinaAirDate = usAirDate + lubridate::days(1))  %>%
        dplyr::group_by(
            #usAirDate, chinaAirDate, show, showTitle)       %>% 
            showTitle)       %>% 
        dplyr::summarize(
            totView=sum(totView),
            totMin=round(sum(totMin)),
            totUniq=sum(totUniq),
            minsPerUniq = round(totMin/totUniq,1),
            minsPerView = round(totMin/totView,1)
            ) %>% 
        dplyr::arrange(desc(showTitle)) %>% 
        dplyr::ungroup() %>%
        dplyr::mutate(
            orderNum=2,
            v1 = dplyr::lead(totView, 1, order_by=dplyr::desc(showTitle)),
            v2 = dplyr::lead(totView, 2, order_by=dplyr::desc(showTitle)),
            v3 = dplyr::lead(totView, 3, order_by=dplyr::desc(showTitle)),
            v4 = dplyr::lead(totView, 4, order_by=dplyr::desc(showTitle)),
            vLast4Avg = (v1+v2+v3+v4)/4.0,
            vVsLast4  = round(100 * (totView - vLast4Avg) / vLast4Avg),
            m1 = dplyr::lead(totMin, 1, order_by=dplyr::desc(showTitle)),
            m2 = dplyr::lead(totMin, 2, order_by=dplyr::desc(showTitle)),
            m3 = dplyr::lead(totMin, 3, order_by=dplyr::desc(showTitle)),
            m4 = dplyr::lead(totMin, 4, order_by=dplyr::desc(showTitle)),
            mLast4Avg = (m1+m2+m3+m4)/4.0,
            mVsLast4  = round(100 * (totMin - mLast4Avg) / mLast4Avg),
            u1 = dplyr::lead(totUniq, 1, order_by=dplyr::desc(showTitle)),
            u2 = dplyr::lead(totUniq, 2, order_by=dplyr::desc(showTitle)),
            u3 = dplyr::lead(totUniq, 3, order_by=dplyr::desc(showTitle)),
            u4 = dplyr::lead(totUniq, 4, order_by=dplyr::desc(showTitle)),
            uLast4Avg = (u1+u2+u3+u4)/4.0,
            uVsLast4  = round(100 * (totUniq - uLast4Avg) / uLast4Avg),
            mpu1 = dplyr::lead(minsPerUniq, 1, order_by=dplyr::desc(showTitle)),
            mpu2 = dplyr::lead(minsPerUniq, 2, order_by=dplyr::desc(showTitle)),
            mpu3 = dplyr::lead(minsPerUniq, 3, order_by=dplyr::desc(showTitle)),
            mpu4 = dplyr::lead(minsPerUniq, 4, order_by=dplyr::desc(showTitle)),
            mpuLast4Avg = (mpu1 + mpu2 + mpu3 + mpu4)/4.0,
            mpuVsLast4  = round(100 * (minsPerUniq - mpuLast4Avg) / mpuLast4Avg),
            mpv1 = dplyr::lead(minsPerView, 1, order_by=dplyr::desc(showTitle)),
            mpv2 = dplyr::lead(minsPerView, 2, order_by=dplyr::desc(showTitle)),
            mpv3 = dplyr::lead(minsPerView, 3, order_by=dplyr::desc(showTitle)),
            mpv4 = dplyr::lead(minsPerView, 4, order_by=dplyr::desc(showTitle)),
            mpvLast4Avg = (mpv1+mpv2+mpv3+mpv4)/4.0,
            mpvVsLast4  = round(100 * (minsPerView - mpvLast4Avg) / mpvLast4Avg)
        ) %>%
        dplyr::select(-c(
            v1,v2,v3,v4,vLast4Avg,
            m1,m2,m3,m4, mLast4Avg,
            u1,u2,u3,u4,uLast4Avg,
            mpu1,mpu2,mpu3,mpu4,mpuLast4Avg,
            mpv1,mpv2,mpv3,mpv4,mpvLast4Avg
            )) %>%
        dplyr::slice(1:N) %>%
        rbind(output)
    
    #========================================================
    # NXT
    #========================================================
    output = pptv_data %>% 
        dplyr::filter(version=='Other', show=='NXT') %>% 
        dplyr::group_by(
            #usAirDate, chinaAirDate, show, showTitle
            showTitle
            ) %>% 
        dplyr::summarize(
            totView = sum(totView),
            totMin  = round(sum(totMin)), 
            totUniq = sum(totUniq),
            minsPerUniq = round(totMin/totUniq,1),
            minsPerView = round(totMin/totView,1)
            ) %>% 
        dplyr::filter(!stringr::str_detect(showTitle, "takeover")) %>%
        dplyr::arrange(desc(showTitle)) %>%
        dplyr::ungroup() %>%
        dplyr::mutate(
            orderNum=3,
            v1 = dplyr::lead(totView, 1, order_by=dplyr::desc(showTitle)),
            v2 = dplyr::lead(totView, 2, order_by=dplyr::desc(showTitle)),
            v3 = dplyr::lead(totView, 3, order_by=dplyr::desc(showTitle)),
            v4 = dplyr::lead(totView, 4, order_by=dplyr::desc(showTitle)),
            vLast4Avg = (v1+v2+v3+v4)/4.0,
            vVsLast4  = round(100 * (totView - vLast4Avg) / vLast4Avg),
            m1 = dplyr::lead(totMin, 1, order_by=dplyr::desc(showTitle)),
            m2 = dplyr::lead(totMin, 2, order_by=dplyr::desc(showTitle)),
            m3 = dplyr::lead(totMin, 3, order_by=dplyr::desc(showTitle)),
            m4 = dplyr::lead(totMin, 4, order_by=dplyr::desc(showTitle)),
            mLast4Avg = (m1+m2+m3+m4)/4.0,
            mVsLast4  = round(100 * (totMin - mLast4Avg) / mLast4Avg),
            u1 = dplyr::lead(totUniq, 1, order_by=dplyr::desc(showTitle)),
            u2 = dplyr::lead(totUniq, 2, order_by=dplyr::desc(showTitle)),
            u3 = dplyr::lead(totUniq, 3, order_by=dplyr::desc(showTitle)),
            u4 = dplyr::lead(totUniq, 4, order_by=dplyr::desc(showTitle)),
            uLast4Avg = (u1+u2+u3+u4)/4.0,
            uVsLast4  = round(100 * (totUniq - uLast4Avg) / uLast4Avg),
            mpu1 = dplyr::lead(minsPerUniq, 1, order_by=dplyr::desc(showTitle)),
            mpu2 = dplyr::lead(minsPerUniq, 2, order_by=dplyr::desc(showTitle)),
            mpu3 = dplyr::lead(minsPerUniq, 3, order_by=dplyr::desc(showTitle)),
            mpu4 = dplyr::lead(minsPerUniq, 4, order_by=dplyr::desc(showTitle)),
            mpuLast4Avg = (mpu1 + mpu2 + mpu3 + mpu4)/4.0,
            mpuVsLast4  = round(100 * (minsPerUniq - mpuLast4Avg) / mpuLast4Avg),
            mpv1 = dplyr::lead(minsPerView, 1, order_by=dplyr::desc(showTitle)),
            mpv2 = dplyr::lead(minsPerView, 2, order_by=dplyr::desc(showTitle)),
            mpv3 = dplyr::lead(minsPerView, 3, order_by=dplyr::desc(showTitle)),
            mpv4 = dplyr::lead(minsPerView, 4, order_by=dplyr::desc(showTitle)),
            mpvLast4Avg = (mpv1+mpv2+mpv3+mpv4)/4.0,
            mpvVsLast4  = round(100 * (minsPerView - mpvLast4Avg) / mpvLast4Avg)
        ) %>%
        dplyr::select(-c(
            v1,v2,v3,v4,vLast4Avg,
            m1,m2,m3,m4, mLast4Avg,
            u1,u2,u3,u4,uLast4Avg,
            mpu1,mpu2,mpu3,mpu4,mpuLast4Avg,
            mpv1,mpv2,mpv3,mpv4,mpvLast4Avg
            )) %>%
        dplyr::slice(1:N) %>%
        rbind(output)
    
    #========================================================
    # CWC
    #========================================================
    output = pptv_data %>% 
        dplyr::filter(version=='Other', show=='CWC') %>% 
        dplyr::group_by(
            #usAirDate, chinaAirDate, show, showTitle
            showTitle
            ) %>% 
        dplyr::summarize(
            totView = sum(totView),
            totMin  = round(sum(totMin)), 
            totUniq = sum(totUniq),
            minsPerUniq = round(totMin/totUniq,1),
            minsPerView = round(totMin/totView,1)
            ) %>% 
        dplyr::arrange(desc(showTitle)) %>%
        dplyr::ungroup() %>%
        dplyr::mutate(
            orderNum=4,
            v1 = dplyr::lead(totView, 1, order_by=dplyr::desc(showTitle)),
            v2 = dplyr::lead(totView, 2, order_by=dplyr::desc(showTitle)),
            v3 = dplyr::lead(totView, 3, order_by=dplyr::desc(showTitle)),
            v4 = dplyr::lead(totView, 4, order_by=dplyr::desc(showTitle)),
            vLast4Avg = (v1+v2+v3+v4)/4.0,
            vVsLast4  = round(100 * (totView - vLast4Avg) / vLast4Avg),
            m1 = dplyr::lead(totMin, 1, order_by=dplyr::desc(showTitle)),
            m2 = dplyr::lead(totMin, 2, order_by=dplyr::desc(showTitle)),
            m3 = dplyr::lead(totMin, 3, order_by=dplyr::desc(showTitle)),
            m4 = dplyr::lead(totMin, 4, order_by=dplyr::desc(showTitle)),
            mLast4Avg = (m1+m2+m3+m4)/4.0,
            mVsLast4  = round(100 * (totMin - mLast4Avg) / mLast4Avg),
            u1 = dplyr::lead(totUniq, 1, order_by=dplyr::desc(showTitle)),
            u2 = dplyr::lead(totUniq, 2, order_by=dplyr::desc(showTitle)),
            u3 = dplyr::lead(totUniq, 3, order_by=dplyr::desc(showTitle)),
            u4 = dplyr::lead(totUniq, 4, order_by=dplyr::desc(showTitle)),
            uLast4Avg = (u1+u2+u3+u4)/4.0,
            uVsLast4  = round(100 * (totUniq - uLast4Avg) / uLast4Avg),
            mpu1 = dplyr::lead(minsPerUniq, 1, order_by=dplyr::desc(showTitle)),
            mpu2 = dplyr::lead(minsPerUniq, 2, order_by=dplyr::desc(showTitle)),
            mpu3 = dplyr::lead(minsPerUniq, 3, order_by=dplyr::desc(showTitle)),
            mpu4 = dplyr::lead(minsPerUniq, 4, order_by=dplyr::desc(showTitle)),
            mpuLast4Avg = (mpu1 + mpu2 + mpu3 + mpu4)/4.0,
            mpuVsLast4  = round(100 * (minsPerUniq - mpuLast4Avg) / mpuLast4Avg),
            mpv1 = dplyr::lead(minsPerView, 1, order_by=dplyr::desc(showTitle)),
            mpv2 = dplyr::lead(minsPerView, 2, order_by=dplyr::desc(showTitle)),
            mpv3 = dplyr::lead(minsPerView, 3, order_by=dplyr::desc(showTitle)),
            mpv4 = dplyr::lead(minsPerView, 4, order_by=dplyr::desc(showTitle)),
            mpvLast4Avg = (mpv1+mpv2+mpv3+mpv4)/4.0,
            mpvVsLast4  = round(100 * (minsPerView - mpvLast4Avg) / mpvLast4Avg)
        ) %>%
        dplyr::select(-c(
            v1,v2,v3,v4,vLast4Avg,
            m1,m2,m3,m4, mLast4Avg,
            u1,u2,u3,u4,uLast4Avg,
            mpu1,mpu2,mpu3,mpu4,mpuLast4Avg,
            mpv1,mpv2,mpv3,mpv4,mpvLast4Avg
            )) %>%
        dplyr::slice(1:N) %>%
        rbind(output)
    
    ############################
    output = output %>% dplyr::arrange(orderNum) %>% dplyr::select(-orderNum)
    if (all_vars==TRUE) {
        output
    } else {
        output %>% select(-totUniq, -minsPerUniq, -uVsLast4, -mpuVsLast4)
    }
}
pptv.offshore.shortform.v2 = function(
    pptv_data,
    N=3,
    all_vars=FALSE
) {
    # Latest 4 Videos, Air Date, Debut, Debut+7, To Date
    # Raw, SD, NXT
    # Metrics: Views, Mins, Mins/View
    #========================================================
    # Raw
    #========================================================
    max_date = max(pptv_data$dataDate)
    output = pptv_data %>% 
        dplyr::filter(
            version=='Other',
            show %in% c("Mon Night Raw", "Smackdown", "NXT")
        ) %>%
        dplyr::mutate(
            debut_mins  = ifelse(dataDate==chinaAirDate, totMin, 0),
            debut_views = ifelse(dataDate==chinaAirDate, totView, 0),
            dp7_mins    = ifelse(dataDate<=chinaAirDate+lubridate::days(6), totMin, 0),
            dp7_views   = ifelse(dataDate<=chinaAirDate+lubridate::days(6), totView, 0),
            idx         = dplyr::recode(show, "Mon Night Raw"=0, "Smackdown"=1, "NXT"=2, .default=3),
            # Have to filter out takeovers from NXT...
            showTitle   = dplyr::recode(
                showTitle, "takeover"="nxt001", "takeover brooklyn"="nxt002", 
                .default=showTitle)
        ) %>%
        dplyr::group_by(show, showTitle) %>%
        dplyr::summarize(
            idx         = max(idx),
            # Have to use chinaAirDate-1 b/c the NXT clips have no 
            #   corresponding usAirDate value
            air_date    = min(chinaAirDate-lubridate::days(1)), 
            debut_views = sum(debut_views[dataDate==min(chinaAirDate)]),
            debut_mins  = sum(debut_mins[dataDate==min(chinaAirDate)]),
            debut_mpv   = round(debut_mins / debut_views, 2),
            dp7_views   = sum(dp7_views[dataDate<=min(chinaAirDate)+lubridate::days(6)]),
            dp7_mins    = sum(dp7_mins[dataDate<=min(chinaAirDate)+lubridate::days(6)]),
            dp7_mpv     = round(dp7_mins / dp7_views, 2),
            td_views    = sum(totView),
            td_mins     = sum(totMin),
            td_mpv      = round(td_mins / td_views, 2)
        ) %>%
        dplyr::top_n(4, wt=air_date) %>%
        dplyr::arrange(idx, desc(showTitle)) %>% 
        dplyr::ungroup() %>%
        dplyr::select(
            showTitle, air_date, 
            debut_views, debut_mins, debut_mpv, 
            dp7_views, dp7_mins, dp7_mpv, 
            td_views, td_mins, td_mpv)
        
    #=====================
    output
        
}



#===================================================================
#  pptv.offshore.topmatches
#===================================================================
#' Top N Cuts
#' 
#' Bla, bla
#' 
#' @param pptv_data
#' 
#' @param N
#' 
#' @param to_csv
#' 
#' @export
#$
pptv.offshore.topmatches = function(
    pptv_data,
    N=20,
    to_csv=FALSE
) {
    
    as_on_dt = max(pptv_data$dataDate + lubridate::days(1), na.rm=TRUE)
    file = paste0(as.character(as_on_dt),"__top",as.character(N),"sf.csv")
    
    topNsf = pptv_data %>% 
        dplyr::filter(version=="Cut", payment=="FREE", dataDate >= as_on_dt - lubridate::days(30)) %>% 
        dplyr::mutate(showTitle=stringr::str_extract(showTitle,"[0-9]+$")) %>%
        dplyr::group_by(game) %>% 
        dplyr::summarize(AirDate=max(usAirDate), Show=max(show), Episode=max(showTitle), 
                         Views=sum(totView), Hours=round(sum(totMin)/60.)) %>% 
        dplyr::select(Show, Episode, AirDate, Match=game, Views, Hours) %>% 
        dplyr::arrange(desc(Views)) %>% 
        dplyr::mutate(
            Views = formatC(Views, format="d", big.mark=","),
            Hours = formatC(Hours, format="d", big.mark=",")
            ) %>%
        dplyr::slice(1:N) 

    if (to_csv==TRUE) {
        con = file(file, open="w", encoding="UTF-8")
        write.csv(topNsf, file=con, fileEncoding="UTF-8")
        close(con)  # Excel still sees chars more bizarre than Chinese symbols
        return(as.data.frame(topNsf))
    } 
    return(as.data.frame(topNsf))
    # Use Google Translate for match names. 
    # Not always straightforward:  Wrestlers names are often translated
    #   phonetically, or with some word that is a synonym of their name, etc.
}




#===================================================================
#  pptv.offshore.web
#===================================================================
#' Compute aggreagted PPTV website numbers.
#' 
#' @param as_on_dt
#' 
#' @param day1
#' 
#' @param ExlWrongWay
#' 
#' @export
#$
# 2017-05-10:  
#    EXL had been doing this wrong for MONTHS.  I never made a
#    a script to check this because the data set is so small
#    and straightforward, I just assumed it was not high
#    priority.  
#  
#    Basically, they would get (recentDate, pageViews) right, but
#    (previousDate, pageViews) wrong.  Similarly, they got 
#    (previousDate, uniqueViews) right, but (recentDate, uniqueViews)
#    wrong.  I found out it was because they were using 
#    (recentDate, uniqueViews) for (previousDate, pageViews), and
#    (previousDate, pageViews) for (recentDate, uniqueViews). 
#
pptv.offshore.web = function(
    as_on_dt=Sys.Date(),
    day1="Monday",
    v2=TRUE
) {
    
    data =  pptv.query.web(as_on_dt, agg=TRUE, day1)
    
    week_data = data %>% 
        dplyr::arrange(dplyr::desc(Date)) %>% 
        dplyr::slice(2:6) %>% 
        tidyr::gather(type, value, 2:7) %>% 
        tidyr::separate(type, into=c("Device", "Type"), sep="_") %>% 
        tidyr::spread(Date,value) %>% 
        dplyr::select(2,1,7,6,5,4,3) %>% 
        dplyr::mutate(
            WoW = paste0(as.character(round(100 * (.[[3]]-.[[4]])/.[[4]])),"%"),
            idx = dplyr::recode(Device,Web=1,App=2,Total=3), 
            Device=ifelse(Device=="App", "Mobile", Device)
        ) 
    
    # We no longer report YTD as of mid-May 2017.
    #  -- to see it, set v2=FALSE
    YTD = data %>%
        dplyr::summarize(
            Web_PV=sum(Web_PV), Web_UV=sum(Web_UV), 
            App_PV=sum(App_PV), App_UV=sum(App_UV),
            Total_PV=sum(Total_PV), Total_UV=sum(Total_UV)
        ) %>% 
        tidyr::gather(type, YTD, 1:6)  %>% 
        tidyr::separate(type, into=c("Device","Type")) %>%
        dplyr::mutate(Device = ifelse(Device=="App", "Mobile", Device)) %>%
        dplyr::select(2,1,3)
    
    # JOIN
    output = week_data %>% 
        dplyr::inner_join(YTD, by=c("Type", "Device")) %>%
        dplyr::arrange(Type,idx) %>% 
        dplyr::mutate(
            avg = (.[[4]]+.[[5]]+.[[6]]+.[[7]])/4.0,
            delta = paste0(round(100*(.[[3]]-avg)/avg), "%")
        ) %>%
        dplyr::select(c(1:6,8,10,12)) 
    
    # Format numbers:  Add commas
    output[[3]] = formatC(output[[3]], format="d", big.mark=",")
    output[[4]] = formatC(output[[4]], format="d", big.mark=",")
    output[[5]] = formatC(output[[5]], format="d", big.mark=",")
    output[[6]] = formatC(output[[6]], format="d", big.mark=",")
    output[[8]] = formatC(output[[8]], format="d", big.mark=",")
    
    # Return
    if (v2==FALSE) 
        output %>% dplyr::select(c(YTD, 3, 4, WoW)) 
    else output %>% dplyr::select(-YTD) 
    
}
#' @param as_on_dt
#' 
#' @export