#' Retrieve PPTV aggregated to the LIVE level.
#' 
#' This function restricts its attention to just Raw and 
#' Smackdown because, ultimately, it is a helper function for 
#' pptv.excel.live.diff and pptv.report.live, which were 
#' developed to serve as checks on metrics and KPIs
#' included in the report generated by the offshore EXL team.  
#' For this reason, it also restricted to LIVE measures
#' with the hope that such modularization might help us more quickly 
#' identify the "what" of "when something is wrong."
#' 
#' ATTRIBUTES OF LIVE VIEWERSHIP:
#'
#'   (a) show=={'Mon Night Raw'|'Smackdown'}
#'   
#'   (b) version=='Full Show'
#'       -- clips are analyzed elsewhere in the PPTV 
#'          report
#'   
#'   (c) audio=={'Mandarin'|'English'}
#'       -- audio=='NULL' in the raw data is a placeholder
#'          for version=='Others', which do not currently
#'          distinguish which language was viewed; i.e.,
#'          version=='Full Show' should have no audio=='NULL'
#'          by definition in the data guide provided by the
#'          PPTV team, so we can safely discard
#'   
#'   (d) type=='LIVE'
#'       -- LIVE always has dataDate == chinaAirDate == usAirDate+1
#'       -- however, there also exists type=='VOD' on this date,
#'          so it is necessary to restrict type to 'LIVE' here
#'       -- setting type=='LIVE' automatically constrains the
#'          dataDate, however I have constraints on both type and 
#'          dataDate for assurance
#'   
#'   (e) dataDate == chinaAirDate
#'       -- we only want to consider rows that have data
#'          recorded on chinaAirDate (i.e., 
#'          dataDate==chinaAirDate) 
#'    
#'  
#' @param pptv_data
#' PPTV data set
#' 
#' @param trail (optional; INTEGER)
#' By default, all live data is  retrieved.  Restrict 
#' to trailing N weeks by specifying integer N.  Note
#' that any decimal are automatically floored.
#' 
#' @param View (optional; {TRUE|FALSE} or {0|1})
#' By default (FALSE) data is returned to parent environment
#' (whether that is to a variable or to screen). By
#' flagging View (TRUE), the data is instead routed to 
#' View()
#' 
#' @param more (optional)
#'
#' @export        
#'  
#============================================================
#  HISTORY
# 
#      2017-03-16, Kevin Urban:  
#          Fcn Name:  pptv_get_raw --> pptv.excel
#          Name of date var:  as_on_dt --> as_on_dt
#      2017-02-06, Kevin Urban (created)
#
#$

pptv.live = function(
    pptv_data,
    trail=0,
    View=FALSE,
    more=FALSE
) {
  
  #-------------------------------------------
  #--------        Get Data       ------------
  #-------------------------------------------
  # PPTV Features:
  #   usAirDate,  chinaAirDate,  dataDate,  show,
  #   showTitle,  game,  type,  audioVersion,
  #   version,  subtitle,  totalViews, 
  #   totalUniques,  totalMins, avgViewsPerUnique,
  #   avgMinsPerView, avgMinsPerUnique
  as_on_dt = as.Date(max(pptv_data$dataDate)) + lubridate::days(1)
  
  #-------------------------------------------
  #--------     Transform Data     -----------
  #-------------------------------------------
  trail=floor(trail) 
  
  # [1] LIVE DATA IN MOST RECENT 5-WK (or 1-WK) WINDOW
  if(trail==0) {
    pptv_live = pptv_data %>% 
        dplyr::filter(
            show %in% c('Mon Night Raw','Smackdown'),
            version  =='Full Show',
            type     == 'LIVE',
            dataDate == chinaAirDate) %>%
      dplyr::arrange(usAirDate,show,desc(audio))
  } else {
    pptv_live = pptv_data %>% 
        dplyr::filter(
            show %in% c('Mon Night Raw','Smackdown'),
            version  == 'Full Show',
            type     == 'LIVE',
            dataDate == chinaAirDate, 
            dataDate >= as_on_dt - lubridate::weeks(trail)) %>%
        dplyr::arrange(usAirDate,show,desc(audio))
  }
  
  # Quick View or More?
  if(more==FALSE) {
      pptv_live = pptv_live %>% 
        dplyr::select(usAirDate, chinaAirDate, show,  audio, subtitle, 
                      totUniq, totMin, totView)
  } else {
      pptv_live = pptv_live %>% 
        select(usAirDate, chinaAirDate, show, type, audio, version, subtitle, payment,
               totUniq, totMin, totView, vpu, mpv, mpu)
  }
  
  if(View==FALSE) { return(pptv_live) } else {View(pptv_live)}
}  

